//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SportSecond.Models
{
    using System;
    using System.Collections.Generic;
    [DisplayName("Событие")]
    public partial class Event : ISelectListable
    {
        public Event()
        {
            this.Teams = new List<Team>();
        }

        public int Id { get; set; }
        [Required]
        [DisplayName("Заголовок")]
        public string Title { get; set; }
        [Required]
        [DisplayName("Описание")]
        public string Description { get; set; }
        [DisplayName("Время")]
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }

        [DisplayName("Адрес")]
        public virtual Location Location { get; set; }
        [DisplayName("Команды")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
