//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SportSecond.Models
{
    using System;
    using System.Collections.Generic;
    [DisplayName("Национальность")]
    public partial class Nationality:ISelectListable
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Название")]
        public string Title { get; set; }
    }
}
