//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SportSecond.Models
{
    using System;
    using System.Collections.Generic;
    [DisplayName("Спортсмен")]
    public partial class Sportsman : ISelectListable
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Ф.И.О.")]
        public string Title { get; set; }
        [Required]
        [DisplayName("Название")]
        [Url]
        public string Image { get; set; }
        [Required]
        [DisplayName("Биография")]
        public string Description { get; set; }

        [DisplayName("Мужик")]
        public bool Gender { get; set; }

        [DisplayName("Тренер")]
        public bool IsCouch { get; set; }

        [DisplayName("День рождения")]
        [DataType(DataType.Date)]
        public System.DateTime Birthday { get; set; }

        [DisplayName("Медали")]
        public int MedalsCount { get; set; }

        [DisplayName("Национальность")]
        public virtual Nationality Nationality { get; set; }
        [DisplayName("Выд спорта")]
        public virtual Sport Sport { get; set; }
        [DisplayName("Команда")]
        public virtual Team Team { get; set; }
    }
}
