//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SportSecond.Models
{
    using System;
    using System.Collections.Generic;
            [DisplayName("Команда")]
    public partial class Team : ISelectListable
    {
        public Team()
        {
            this.Memebers = new List<Sportsman>();
            this.Events = new List<Event>();
        }

        public int Id { get; set; }
        [Required]
        [DisplayName("Название")]
        public string Title { get; set; }
        [Required]
        [DisplayName("Изображение")]
        [Url]
        public string Image { get; set; }

        [DisplayName("Челены команды")]
        public virtual ICollection<Sportsman> Memebers { get; set; }

        [DisplayName("События")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
